title: MUDInt
description: A C++ library for interpreting and managing player inputs in a text-based Multi-User Dungeon (MUD).
author: Enrico Fraccaroli
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
social:
  email: enrico.fraccaroli@univr.it
